### ISSUE TITLE
ProxyKick

### ISSUE THREAD

**Issue by Ula492** [Shortninja66/StaffPlus#10]
If I do /staff it gives me [PROXY] LOST CONNECTION - server is on a Bungeecord

**Comment by Shortninja66** [comment]
what server version is it? what version of bungeecord is it? where is the staff+ plugin located on your server? is there any other error?

**Comment by Ula492** [comment]
1.8.8 - latest bungeecord. its located on the plugins folder. No errors except PROXY LOST CONNECTION as soon as i do /staff

**Comment by Shortninja66** [comment]
i can't do anything for you if there's no errors.

**Comment by Ula492** [comment]
I only got this: 
22.07 14:16:44 [Disconnect] User Ula492 has disconnected, reason: Internal Exception: java.lang.NoSuchMethodError: org.inventivetalent.packetlistener.handler.SentPacket.getPacketValue(I)Ljava/lang/Object;

**Comment by Shortninja66** [comment]
Okay, it could have been a shading issue. I am not home right now so I am unable to update the plugin.

You can fix this by disabling packet listening in your config. It can be found at the bottom of the file and should be changed to something like [this](http://pastebin.com/sKgM9z8s):

**Comment by Ula492** [comment]
I downloaded the latest version of your plugin & still not fixed :( 

I did what you said to do, still happening :/

[16:59:45 INFO]: Ula492 lost connection: Internal Exception: java.lang.NoSuchMethodError: org.inventivetalent.packetlistener.handler.SentPacket.getPacketValue(I)Ljava/lang/Object;

Also when I do staff 

17:05:37 INFO]: Ula492 issued server command: /staff
[17:05:37 INFO]: Unknown command. Type "/help" for help.
[17:05:37 INFO]: Unknown command. Type "/help" for help.
[17:05:44 INFO]: Ula492 lost connection: Internal Exception: java.lang.NoSuchMethodError: org.inventivetalent.packetlistener.handler.SentPacket.getPacketValue(I)Ljava/lang/Object;
[17:05:44 INFO]: Unknown command. Type "/help" for help.
[17:05:44 INFO]: Unknown command. Type "/help" for help.

Error is also happening with out bukkit.

**Comment by Shortninja66** [comment]
like i said, disable packet handling in the config file.

**Comment by Ula492** [comment]
I did.
Still happening.

**Comment by Shortninja66** [comment]
i'll look into your issue a bit more while i work on the next patch. i don't see anybody else getting this error, so it could be explicitly your side

**go ahead and update to the latest version of staff+, 3.0.8, and see if it works fine. i made sure that packet methods are not accessed if there are no packets to check.**
