### ISSUE TITLE
spigot not finding plugin

### ISSUE THREAD

**Issue by john-sp** [Shortninja66/StaffPlus#11]
I restarted my server after installing staff+ configured it restarted it again and no commands are working or the staff chat. Is it something i am doing  or is it a bug some where i am using java 8 and spigot for minecraft 1.8.3

**Comment by john-sp** [comment]
It says it can not load config,yml

**Comment by Shortninja66** [comment]
make sure your user has read/write permissions for your operating system.

**Comment by john-sp** [comment]
![capture99](https://cloud.githubusercontent.com/assets/20563885/17007381/de520b12-4ead-11e6-8a0a-1ef8bb56e3f5.JPG)
i am an admin

**Comment by john-sp** [comment]
![capture99](https://cloud.githubusercontent.com/assets/20563885/17007475/a7937b3c-4eae-11e6-8217-370bb39c40b7.JPG)

**Comment by Shortninja66** [comment]
send me your entire config file.

**Comment by john-sp** [comment]
_Here it is_
http://pastebin.com/e6qsLznX

**Comment by Shortninja66** [comment]
i don't see anything wrong with it. try regenerating the config by deleting it.

and jesus, please use pastebin next time.

**Comment by john-sp** [comment]
It did not work is there a different version i can try?

**Comment by Shortninja66** [comment]
can you define how it does not work?

yes there are several other versions on the spigot page, but they may have bugs.
