### ISSUE TITLE
%ticket% Variable not work

### ISSUE THREAD

**Issue by YukiHaix86** [Shortninja66/StaffPlus#12]
The variable in the Lang data %ticket% is not working when someone makesa ticket it says Your ticket has been created %ticket%

**Comment by Shortninja66** [comment]
what message are you referring to? include the node (for example, "ticket-submitted").

**Comment by YukiHaix86** [comment]
Only when a ticket is created / submitted all other messages are working with the placeholder %ticket%

**Comment by YukiHaix86** [comment]
And when i respond to a ticket there are two messages to me and no to the ticket creator x3

**Comment by Shortninja66** [comment]
i will ask once again, what message exactly are you referring to?

and what ticket are you responding to? if you are responding to a ticket to your self then of course there will be two messages sent to you. i've tested it and it works fine.

**Comment by YukiHaix86** [comment]
The ticket created message and i have 2 accounts were one is the player the another one is supporter and if the supporter replies he gets 2 messages but the player nothing

**Comment by Shortninja66** [comment]
i'll look into it. if there is a bug it will be patched in the next update (by tomorrow)
