### ISSUE TITLE
Random  ErrorS ( 4 )

### ISSUE THREAD

**Issue by TriumphLord** [Shortninja66/StaffPlus#14]
http://pastebin.com/BP4dTYNf

2 different errors i get

I get a playerjoievent error as well

i ALSO Get this when i start the server 28.08 00:18:22 [Server] WARN [StaffPlus] Default system encoding may have misread config.yml from plugin jar

**Comment by Shortninja66** [comment]
what version of staff+ and bukkit/spigot are you using? try removing your packets and sounds in the advanced sections (leaving the nodes blank).

also, please use pastebin if you post stack traces.
