### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Firestar311** [Shortninja66/StaffPlus#21]
09.12 21:58:54 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_101] 09.12 21:58:54 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 09.12 21:58:54 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 09.12 21:58:54 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 09.12 21:58:54 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 09.12 21:58:54 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 09.12 21:58:54 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 09.12 21:58:54 [Server] INFO at net.shortninja.staffplus.Tasks.run(Tasks.java:49) ~[?:?] 09.12 21:58:54 [Server] INFO at net.shortninja.staffplus.Tasks.decideAutosave(Tasks.java:101) ~[?:?] 09.12 21:58:54 [Server] INFO java.lang.NullPointerException 09.12 21:58:54 [Server] WARN [StaffPlus] Task #654 for StaffPlus v3.2.1 generated an exception 09.12 21:58:52 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_101] 09.12 21:58:52 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 09.12 21:58:52 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 09.12 21:58:52 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 09.12 21:58:52 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 09.12 21:58:52 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 09.12 21:58:52 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 09.12 21:58:52 [Server] INFO at net.shortninja.staffplus.Tasks.run(Tasks.java:49) ~[?:?] 09.12 21:58:52 [Server] INFO at net.shortninja.staffplus.Tasks.decideAutosave(Tasks.java:101) ~[?:?] 09.12 21:58:52 [Server] INFO java.lang.NullPointerException 09.12 21:58:52 [Server] WARN [StaffPlus] Task #654 for StaffPlus v3.2.1 generated an exception

**Comment by Shortninja66** [comment]
small bug with updating frozen users, will be fixed in next patch!
