### ISSUE TITLE
Launcher doesn't work

### ISSUE THREAD

**Issue by raiderpvper** [Shortninja66/StaffPlus#25]
When you do /staff and do not have /op the launcher (compass) doesn't work at all. It will only work if you have op or are in the owner group with all the permissions. I gave the class that I want the compass to work for the permission staff.compass and for some reason it still wont work. Everything else works fine.

**Comment by Shortninja66** [comment]
they need permissions for staff mode to use the compass. read the configuration file for the correct permissions.

**Comment by raiderpvper** [comment]
I gave them permessions for staff mode and to use the compass

**Comment by Shortninja66** [comment]
are they actually in staff mode while trying to use the compass? have you tried restarting your server? (sometimes nbt tags break after a bit)

**Comment by raiderpvper** [comment]
yes they are in staff mode when trying. I restarted it and im still having the same problem

**Comment by Shortninja66** [comment]
can you send me your configuration file, latest log file, and your permissions file?
