### ISSUE TITLE
Can drop and pickup items xD

### ISSUE THREAD

**Issue by arturek1666** [Shortninja66/StaffPlus#29]
Even with settings:
# Whether or not a player is allowed to drop/pickup items while in staff mode.
  item-change: false

I can pick up items and drop them with makes players know i am spying xD please fix

**Comment by Shortninja66** [comment]
you have to be in staff mode for it to take effect.

**Comment by arturek1666** [comment]
I am xD

**Comment by arturek1666** [comment]
Using paperspigot 1.11.2 newest one,

**Comment by Shortninja66** [comment]
paperspigot is not supported.
