### ISSUE TITLE
Strip Command

### ISSUE THREAD

**Issue by AaronL98** [Shortninja66/StaffPlus#30]
Whenever using the /strip <player> command, the player's helmet and chest plate are completely removed, vanished.

I'm unsure if this is a known bug, however I haven't seen it working yet.

Using 1.8.8

**Comment by Shortninja66** [comment]
that's the entire purpose of the strip command

**Comment by AaronL98** [comment]
Leggings and boots are returned to the inventory. Helmet and chestplate are not, yet removed from the armor slot.
Fail to see how that's how its meant to behave lol.
