### ISSUE TITLE
couple of issues

### ISSUE THREAD

**Issue by arturek1666** [Shortninja66/StaffPlus#31]
Using: paperspigot 11.2
In config
  # Whether or not a player is allowed to drop/pickup items while in staff mode.
  item-change: false

Basically when i am in staff mode i can pickup items with i wasn't able to do it before. Even settings are done good. Also people can here the sound of chests.

No error in the console by the way so can't really do that.

**Comment by tempayyalf** [comment]
Yo for some reason he won't add me back on skype. Anyone have an answer?

**Comment by memedogsl123** [comment]
Wtf dude he can't help you with the errors in his plugin.. theres errors in his life now

**Comment by rianexists** [comment]
@tempayyalf [A Reflection - md_5 on SpigotMC](https://www.spigotmc.org/threads/a-reflection.219197/)
@memedogsl123 Yes, but @tempayyalf won't necessarily know that.
@arturek1666 You aren't meant to use PaperSpigot. Try using regular Spigot and @mention me if it still doesn't work.

**Comment by Legoman99573** [comment]
Refer to #34
