### ISSUE TITLE
/Strip Bug [BAD BUG]

### ISSUE THREAD

**Issue by Owen1212055** [Shortninja66/StaffPlus#35]
Hello, there is a bug where /strip would not take your armor off. Though It will put it in your inventory, It wouldnt remove it from your Armor slots! But if you have all your armor on, It will only take the helmet and the Chestplate, but the player will be given the boots and leggings!

**Comment by nightdepression** [comment]
Author dead..

**Comment by birkhofflee** [comment]
@Owen1212055  Shortninja passed away.

**Comment by Legoman99573** [comment]
#34 He isnt alive dude. Why are people expecting an update when the author isnt alive?

**Comment by FFY00** [comment]
In which version is this happening?
