### ISSUE TITLE
Color Prefixes

### ISSUE THREAD

**Issue by MichaelMBrown** [Shortninja66/StaffPlus#4]
Hello! One of the issues i have found quite recently is the & prefix, when it would load up the _default_ config, I would get error symbols in my chat, I have resorted to the \xa7<colorcode> feature to remove this problem, to recap, the &<color> does not work for me. Thanks!

**Comment by Shortninja66** [comment]
send a screenshot of these "error symbols", i am almost sure you're talking about utf-8 characters (meaning this is not my fault, but your text editor's fault).

**Comment by MichaelMBrown** [comment]
Sorry for not Supplying pictures, the pictures for the errors are in this link http://imgur.com/a/AxQ8G

**Comment by Shortninja66** [comment]
like i said, this is not my side. please refer to the issue [here](https://github.com/Shortninja66/StaffPlus/issues/3).

characters like "»", "ä", "å", and etc. encode into strange characters if the file is not saved as UTF-8.
