### ISSUE TITLE
No revive feature

### ISSUE THREAD

**Issue by Wqrld** [Shortninja66/StaffPlus#60]
HI, you spigot page states that you have a revive feature but i cant find it, where is it located? (like which command)

**Comment by Wqrld** [comment]
theres a eomfom2e command registered but i doubt thats it?

**Comment by Redned235** [comment]
Unfortunately, the author of this plugin is no longer with us (read https://www.spigotmc.org/threads/a-reflection.219197/ for more info). However, a fork of the plugin is being maintained here https://github.com/Qballl/StaffPlus where you can submit issues that will be looked at. Here is a link to the maintained plugin as well: https://www.spigotmc.org/resources/staff-the-ultimate-moderation-plugin-1-7-1-13.41500/.

**Comment by Wqrld** [comment]
I've seen it. sad to hear
