### ISSUE TITLE
/staff does not work

### ISSUE THREAD

**Issue by ItzDerock** [Shortninja66/StaffPlus#62]
Whenever I execute /staff this error pops up: 
`null org.bukkit.command.CommandException: Unhandled exception executing 'staff' in net.shortninja.staffplus.server.command.cmd.mode.ModeCmd(staff)`

It seems like this line is causing the error: `if(StaffPlus.get().modeCoordinator.isInMode(player.getUniqueId()))`

So either `StaffPlus.get()` is returning `null` or I don't have a UUID.

Here is the full error: https://pastebin.com/vbezhg6V

When I do /staff DerockGamer (my IGN) it's a different error. https://pastebin.com/0b21pPYz

Says something about `net.shortninja.staffplus.util.PermissionHandler.isOp(PermissionHandler.java:47)` returning null

Which is this line: `return sender.hasPermission(StaffPlus.get().options.permissionWildcard);`

I can't seem to figure out why this would return null.
It could be my config, I'm guessing `return sender.hasPermission(StaffPlus.get().options.permissionWildcard);` gets a permission from the config.

**Comment by Legoman99573** [comment]
#34 not going to ever get a response unless you find a fork of this project
